fix: correct checking of chromium

diff --git a/.github/workflows/pr-review.yml b/.github/workflows/pr-review.yml
--- a/.github/workflows/pr-review.yml
+++ b/.github/workflows/pr-review.yml
@@ -43,10 +43,19 @@ jobs:
             **.Qmd
             **.qmd
 
+      # The Check Chromium step appears necessary to avoid a crash/hang when rendering PDFs
+      # https://github.com/quarto-dev/quarto-actions/issues/45#issuecomment-1562599451
       - name: Check chromium
+        if: ${{ runner.os == 'Linux' }}
         run: |
-          echo $(which chromium-browser)
-          $(which chromium-browser) --headless https://www.chromestatus.com
+          CHROMIUM_PATH=$(which chromium-browser)
+          if [ -x "$CHROMIUM_PATH" ]; then
+            echo $CHROMIUM_PATH
+            "$CHROMIUM_PATH" --headless --no-sandbox --disable-gpu --renderer-process-limit=1 https://www.chromestatus.com || echo "Headless run failed"
+          else
+            echo "No Chromium executable found"
+          fi
+        shell: bash
 
       - name: Render the new quarto files
         if: steps.new-qmd-files.outputs.any_changed == 'true'
